### ISSUE TITLE
Admin website (byte unit)

### ISSUE THREAD

**Issue by jpenner123** [SadBatman/cryptonote-sumokoin-pool#8]
Please change the following function from

	function getReadableHashRateString(hashrate) {
		hashrate = hashrate || 0;
		var i = 0;
		var byteUnits = [' H', ' KH', ' MH', ' GH', ' TH', ' PH' ];
		while(hashrate > 1000) {
			hashrate = hashrate / 1000;
			i++;
		}
		return parseInt(hashrate).toFixed(2) + byteUnits;
	}

to

	function getReadableHashRateString(hashrate) {
		hashrate = hashrate || 0;
		var i = 0;
		var byteUnits = [' H', ' KH', ' MH', ' GH', ' TH', ' PH' ];
		while(hashrate > 1000) {
			hashrate = hashrate / 1000;
			i++;
		}
		return parseInt(hashrate).toFixed(2) + byteUnits[i];
	}

This way, the unit is displayed properly.

Thx for your support and maintaining this!

**Comment by SadBatman** [comment]
Thanks for reporting this!  It seems we already fixed this in our code:
https://github.com/SadBatman/cryptonote-sumokoin-pool/blob/master/website/pages/home.html#L407

Did you get your pool from a different fork perhaps?

**Comment by SadBatman** [comment]
I'm blind. It seems we have the same function in two locations.
It's fixed now:
https://github.com/SadBatman/cryptonote-sumokoin-pool/commit/f62f2863a62affa0d5891bed99eb2bb023121262

Thanks for reporting!!

**Comment by jpenner123** [comment]
Hi SadBatman,

 

No problem…

I had used the billaue version (https://github.com/sumoprojects/cryptonote-sumokoin-pool) and wanted to upgrade as billaue indicated that new

Features can be found on your fork. After checking the website files on your fork, I realized that the problem I had already fixed on my pool still existed on

Your fork.

 

If you don’t mind me asking… what I was wondering is if you expect any problems upgrading from billaue’s version to yours. I have seen that some data

structures have changed and I would like to upgrade without anything breaking.

 

Any advice would be much appreciated!

 


Cheers,

 

John
